conf .defaults
mode strict

unsetenv SSH_AUTH_SOCK
unsetenv SSH_ASKPASS

# Give ro access to chezmoi source dir, and apply on startup.
rdir? .local/share/chezmoi
command chezmoi init --apply --promptString 'name=jai,email=jai@example.org,work_email=jai@example.org,work_git_dir=~/git'; "$0" "$@"
